const HTTP_STATUS_CODES = {
    OK: 200,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    METHOD_NOT_ALLOWED: 405,
    CONFLICT: 409,
    INTERNAL_SERVER_ERROR: 500,
};

const PER_PAGE = {
    EVENTS_PER_PAGE: 10
};


module.exports = {
    HTTP_STATUS_CODES,
    PER_PAGE
};